### PR TITLE
Add GHC 8.0.1 support

### PR DESCRIPTION
**Pull request by HWoidt**
This
1. Adds GHC 8.0.1 support alongside GHC 7.10.3
2. Adds TravisCI configuration for build-testing the package

@ugeorge Can you please enable TravisCI for this repository?

### CODE REVIEW

**Comment by ugeorge** [comment]
@HWoidt it is enabled: [Build Status](https://travis-ci.org/forsyde/forsyde-deep)

**Comment by ugeorge** [comment]
@HWoidt ´parameterized-data´ is not on HackageDB yet, thus the check will fail. I will try to do that until tomorrow.

**Comment by HWoidt** [comment]
@ugeorge thanks :)

**Comment by ugeorge** [comment]
@HWoidt all dependencies are now uploaded to HackageDB. It should build properly.

**Pull request merged**
